W-11596870-document usage metrics
mulesoft/docs-anypoint-datagraph pull request #101
Opened 2022-08-24 18:38 UTC by IsaacEldridge

2022-08-25 12:31 UTC, ibottero requested changes

2022-08-25 15:49 UTC, IsaacEldridge commented on modules/ROOT/pages/usage-metrics.adoc
> +DataGraph enables you to track metrics so you’re always aware of your usage relative to the limits specified for your business groups. Use these metrics to track the total number of downstream API ca
got it.

2022-08-25 15:51 UTC, ibottero submitted a review, later dismissed

2022-09-12 17:59 UTC, IsaacEldridge commented on modules/ROOT/pages/usage-metrics.adoc
> +* Mule Messages
```suggestion
```

2022-09-27 22:53 UTC, gbattist approved these changes
This looks fine. My only doubt is related to the Custom Dash general initial goals "Correlating diverse metrics,
Performing comparative analysis, etc". Should we include it? Since this is DG specific and I believe these characteristics are general for Custom Dash we may want to skip them. No big deal, so if you believe it completes the doc is ok to me.

2022-09-27 23:08 UTC, merged